services:
  postgresql:
    image: postgres:16
    container_name: sc-postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: spring_collector
    ports:
      - "5432:5432"
    volumes:
      - .data/postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d spring_collector"]
      interval: 10s
      timeout: 5s
      retries: 5

  influxdb:
    image: influxdb:2.7
    container_name: sc-influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123456
      DOCKER_INFLUXDB_INIT_ORG: spring-watch
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: sw-token-2024
      INFLUXD_CONFIG_PATH: /etc/influxdb2/influxdb.toml
      GOMEMLIMIT: 900MiB
      GOGC: 50
    volumes:
      - .data/influxdb_data:/var/lib/influxdb2
      - ./influxdb.toml:/etc/influxdb2/influxdb.toml
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
  influxdb_data:
