reporting-disabled = true
log-level = "info"

[data]
  cache-max-memory-size = 268435456
  cache-snapshot-memory-size = 26214400
  cache-snapshot-write-cold-duration = "10m"
  compact-full-write-cold-duration = "4h"
  max-concurrent-compactions = 2
  max-index-compaction-file-size = "1m"

[coordinator]
  query-timeout = "60s"
  max-concurrent-queries = 50
  max-select-point = 5000000
  max-select-series = 1000
  max-select-buckets = 5000

[query]
  memory-bytes-quota = 536870912
  initial-memory-bytes-quota-per-query = 67108864
  max-memory-bytes-per-query = 268435456

[http]
  max-body-size = 33554432
  max-connection-limit = 0
  max-concurrent-write-limit = 0
