@echo off
setlocal

set AGENT_JAR=%~dp0target\opentelemetry-javaagent.jar
set APP_JAR=%~dp0target\mock-test-1.0.0.jar
set APP_PORT=8081
set METRICS_PORT=9464

if not exist "%AGENT_JAR%" (
    echo [ERROR] %AGENT_JAR% not found. Run 'mvn package' first to copy OTel agent jar.
    exit /b 1
)
if not exist "%APP_JAR%" (
    echo [ERROR] %APP_JAR% not found. Run 'mvn package' first.
    exit /b 1
)

set "JAVA_EXE=java"
if defined JAVA_HOME (
    set "JAVA_EXE=%JAVA_HOME%\bin\java"
)

echo [INFO] ===========================================
echo [INFO] mock-test with OTel Java agent (full instrumentation)
echo [INFO] Java:      %JAVA_EXE%
echo [INFO] Agent:     %AGENT_JAR%
echo [INFO] App:       %APP_JAR%
echo [INFO] App port:  %APP_PORT%
echo [INFO] Metrics:   :%METRICS_PORT%/metrics
echo [INFO] ===========================================

"%JAVA_EXE%" -javaagent:"%AGENT_JAR%" ^
  -DOTEL_SERVICE_NAME=mock-test ^
  -DOTEL_RESOURCE_ATTRIBUTES=service.name=mock-test,service.namespace=spring-watch,deployment.environment=test ^
  -DOTEL_METRICS_EXPORTER=prometheus ^
  -DOTEL_LOGS_EXPORTER=none ^
  -DOTEL_TRACES_EXPORTER=none ^
  -DOTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0 ^
  -DOTEL_EXPORTER_PROMETHEUS_PORT=%METRICS_PORT% ^
  -DOTEL_SEMCONV_STABILITY_OPT_IN=http ^

  REM ==== 默认开关(防御性) ====
  -DOTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED=true ^

  REM ==== JVM / Runtime / 系统级 ====
  -DOTEL_INSTRUMENTATION_RUNTIME_JVM_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_OSHI_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JMX_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_EXECUTORS_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_SCHEDULING_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_MICROMETER_ENABLED=true ^

  REM ==== Web / HTTP 服务端 ====
  -DOTEL_INSTRUMENTATION_SPRING_WEB_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_SPRING_CORE_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_SPRING_SCHEDULING_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_TOMCAT_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_SERVLET_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JAKARTA_SERVLET_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_HTTP_SERVER_ENABLED=true ^

  REM ==== Web / HTTP 客户端 ====
  -DOTEL_INSTRUMENTATION_HTTP_CLIENT_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_HTTP_URL_CONNECTION_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_APACHE_HTTPCLIENT_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_APACHE_HTTPASYNCCLIENT_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_OKHTTP_ENABLED=true ^

  REM ==== DB / 连接池 / ORM ====
  -DOTEL_INSTRUMENTATION_JDBC_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JAKARTA_JDBC_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_HIKARICP_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_TOMCAT_JDBC_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_C3P0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_DBCP_2_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_VIBUR_DBCP_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_HIBERNATE_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JPA_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_ELASTIC_TRANSACTION_2_0_ENABLED=true ^

  REM ==== 日志 appender + MDC(给日志打 trace_id) ====
  -DOTEL_INSTRUMENTATION_LOGBACK_APPENDER_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_LOGBACK_MDC_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_LOG4J_APPENDER_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_LOG4J_MDC_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_LOG4J2_APPENDER_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_LOG4J2_MDC_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JUL_APPENDER_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JUL_MDC_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JBOSS_LOGMANAGER_APPENDER_1_0_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_JBOSS_LOGMANAGER_MDC_1_0_ENABLED=true ^

  REM ==== 注解 / AOP ====
  -DOTEL_INSTRUMENTATION_ANNOTATIONS_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_CODE_FUNCTION_METRICS_ENABLED=true ^
  -DOTEL_INSTRUMENTATION_ASPECTJ_ENABLED=true ^

  REM ==== AOT(native image) ====
  -DOTEL_INSTRUMENTATION_NATIVE_ENABLED=true ^

  REM ==== 内部 ====
  -DOTEL_INSTRUMENTATION_INTERNAL_ENABLED=true ^

  -Dserver.port=%APP_PORT% ^
  -jar "%APP_JAR%"

endlocal
